### PR TITLE
Support for multiple thresholds

### PR DESCRIPTION
**Pull request by osteenbergen**
- options.thresholds = [100, 75, 50, 25]; #3 
- Added some maskPadding to prevent some clipping on the bottom and top of the graph #8 
- Added prefix to support multiple graphs on a single page #11 

chartist_thresholds

### CODE REVIEW

**Comment by gionkunz** [comment]
Hey thanks! I appreciate the feature! Will look into the PR soon.

**Comment by robkaper** [comment]
Precisely what I need, would love for this to be included.

**Comment by xuancongwen** [comment]
@gionkunz Any chance of this getting a code review?

**Comment by maxbond2** [comment]
Used this plugin mod for one of my project - it saved a lot of time for me! @osteenbergen, thank you very much!  

One note. When several charts initialised with different thresholds, you have to manually set uniqe mask names for each chart!

**Comment by ghost** [comment]
Do you have some example code for this? I'm struggling to set up multiple thresholds and style each differently, I only have ct-threshold-below and ct-threshold-above to work with?

**Comment by osteenbergen** [comment]
Depending on the `prefixThreshold` setting you have `area-<index>` available.

`option.thresholds = [75, 50, 25]`

* above: 75 and higher
* area-0: between 75 and 50
* area-1: between 50 and 25
* below: 25 and lower

```css
.ct-point {
  stroke-width: 5px;
}
.ct-point.ct-threshold-above {
  stroke: green;
}
.ct-point.ct-threshold-area-0 {
  stroke: yellow;
}
.ct-point.ct-threshold-area-1 {
  stroke: orange;
}
.ct-point.ct-threshold-below {
  stroke: red;
}
```

**Comment by osteenbergen** [comment]
@gionkunz Its been a year, any luck on merging this PR? Do you require improvements?

**Comment by markterrill** [comment]
great stuff! Seems quite a lot of the chartist repo's are not being maintained

**Comment by osteenbergen** [comment]
Closing this PR as this project is not maintained....

**Pull request closed without merging**
