### PR TITLE
Module import and dependencies update

### LINKED ISSUE #12: "Chartist is not defined" exception while using "import" syntax
# Description 
While using `import` syntax and a module bundler with chartist-plugin-threshold it result with an error:
`Chartist is not defined`.

# Workaround
Use `require()` after set `window.Chartist`.

### PR DESCRIPTION
**Pull request by marcalexiei**
- update all dependencies.
- add `grunt` and `grunt-newer` as dev dependencies.
- add `chartist` as peer dependency.
- add `chartist` in `umd` process to fix error while using `import` (fix #12).
- add `license` field to `package.json`.
- add test which check class existence after chart drawing.
- remove unused grunt param in `tasks` js files.

### CODE REVIEW

**Comment by marcalexiei** [comment]
Hi @gionkunz,
any change to get this merged?

Thanks

**Comment by siddharthk06** [comment]
Please merge these changes

**Comment by gionkunz** [comment]
Thanks! And sorry for the delay...

**Comment by siddharthk06** [comment]
Thanks for responding. I am getting the older version on installing. I think we need to publish to npm registry

**Comment by aesy** [comment]
When will this fix be published?

**Comment by Patronics** [comment]
Joining in to request this be published to npm.

**Pull request merged**
